### ISSUE TITLE
CFRunLoopSource does not convert

### ISSUE THREAD

**Issue by Brent-styles** [Rushabhshroff/flutter_system_proxy#22]
Im running off of main branch, and when I try and build an xcode ipa, im getting this feedback:

Swift Compiler Error (Xcode): Cannot convert value of type 'Unmanaged<CFRunLoopSource>' to expected argument type 'CFRunLoopSource?'
/Users/runner/.pub-cache/git/flutter_system_proxy-a2ebbf5f93b2f2b35aa72fbc591d97cc4244a832/ios/Classes/SwiftFlutterSystemProxyPlugin.swift:107:44

**Comment by Brent-styles** [comment]
using 0.1.1 worked.

**Comment by acacioveit** [comment]
same here
