### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by nullhandler** [Rushabhshroff/flutter_system_proxy#4]
I used the plugin on our app.  For android its working fine. But for iOS devices in browserstack, the proxy is returned as DIRECT. So, it just directly calls the api from Browserstacks server itself. Is this plugin tested on iOS devices on browserstack?

**Comment by Rushabhshroff** [comment]
Are you using local testing and is force local enabled?

**Comment by nullhandler** [comment]
yes. both are enabled @Rushabhshroff

**Comment by nullhandler** [comment]
@Rushabhshroff any updates on this?

**Comment by Rushabhshroff** [comment]
@selvasoft Yes bug has been identified. When force local is enabled Ios plugin application tries to fetch PAC configuration from the user's environment instead of browserstack. Working on a fix

**Comment by nullhandler** [comment]
thank you so much @Rushabhshroff

**Comment by Rushabhshroff** [comment]
@selvasoft Fix has been merged

**Comment by nullhandler** [comment]
@Rushabhshroff thank you so much for the quick fix  🎊
